[package]
name = "xgifwall"
version = "0.1.0"
authors = ["Frank Großgasteiger <frank@pixelgerecht.de>"]
edition = "2018"
links = "X11"
build = "build.rs"

[dependencies]
image = "0.23.8"
x11 = "2.18.2"

