[package]
name = "xgifwall"
version = "0.1.0"
authors = ["Frank Großgasteiger <frank@pixelgerecht.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
